### PR TITLE
Customized Message Box

### PR DESCRIPTION
**Pull request by SkullyKiddo**
This would provide a custom message box to the end user, with a WPF template.

### CODE REVIEW

**Comment by Toyz** [comment]
There's conflicts I like the system but you need to fix the conflicts

**Comment by Toyz** [comment]
Build failed can't merge and it's a merge with cation please make it pass build before we can accept

**Comment by SkullyKiddo** [comment]
Toyz, I believe that everything is working now.

**Comment by Toyz** [comment]
good to go :P merging now

**Comment by SkullyKiddo** [comment]
I'd poke this bitch around a little just to check if the contrast and alignments are okay :D

**Comment by Toyz** [comment]
i can't build the dll at all it get errors in building it now

**Comment by Toyz** [comment]
TargetType CLR is not found in the app.xaml, any ideas to how you fixed this issue

**Comment by SkullyKiddo** [comment]
I haven't got such error. I've used the Nuget package manager to get the packages automatically. I'll try cleaning everything and see if I can reproduce.

**Comment by SkullyKiddo** [comment]
I've cleaned it all and managed to compile with no problems. Try erasing the whole folder and "re-cloning" if you've got no changes.

**Pull request merged**
