### PR TITLE
Image pixelate

### PR DESCRIPTION
**Pull request by robertiagar**
Adding an option to pixelate images before setting them as login background.

### CODE REVIEW

**Comment by darth62969** [comment]
why do we need this?

**Comment by Krutonium** [comment]
We decided to merge this, seems like an interesting idea.

**Comment by KaleidonKep99** [comment]
Login Screen Minecraft Edition confirmed?

**Comment by Krutonium** [comment]
Perhaps.

**Comment by robertiagar** [comment]
this was an idea a friend of mine had... i was messing around with pixelating images (it gives a nice effect) and he said that it might be nice to have on a login changer. since this one is open source, i thought i'd give it a shot. didn't expect to be merged this quickly. thanks! :shipit:

**Comment by Krutonium** [comment]
np ;)

**Comment by robertiagar** [comment]
although I might expand it a bit. I should add code that shows a preview of how the pixelated image looks like. thing is, on slower cpu's (i have a 4790k and the pixelation is super fast) it takes a few seconds (around 17-20 seconds depending on the size of the image). i'm not that good of parallelizing code and the pixelation code can be parallelized (a core/per pixel block). can any of you help me with that?

**Comment by Krutonium** [comment]
Ironically I don't know C# very well, perhaps @Toyz can?

**Comment by robertiagar** [comment]
After a few brain squeezing sessions and a bit of googling, I finally managed to speed up the pixelate method. Here are my results:

Starting normal...
Done in: "00:00:16.0090440".
Starting using lockbits...
Done in: "00:00:05.0183926".
Starting using lockbits parallel...
Done in: "00:00:02.1073029".

This is with an image of 5573 x 3715 and a pixelate size of 100.

**Pull request merged**
